spring:
  main:
    lazy-initialization: true
logging:
  level:
    root: INFO
    org:
      eugens21:
        luma: DEBUG
luma:
  url: https://magento.softwaretestingboard.com/
  userInterface:
    enabled: true
    playwright:
      #      createOptions:
      #        key: "value"
      browser:
        width: 2560
        height: 1440
        type: chromium
        launchOptions:
          #          args:
          #            - --my-arg
          #            - --my-arg1
          #            - --my-arg2
          #          channel: chrome
          #          chromiumSandbox: false
          devTools: false
          downloadsPath: "${user.home}/Downloads"
          #          env:
          #            key: "value"
          #            key1: "value1"
          #          executablePath: ""
          #          firefoxUserPrefs:
          #            key: "value"
          #            key1: "value1"
          headless: false
          #          ignoreAllDefaultArgs: false
          #          ignoreDefaultArgs:
          #            - arg1
          #            - arg2
          #            - arg3
          #          proxy: "localhost://my.proxy/server"
          #          slowMo: 2.0
          timeout: 10000
          tracesDir: "${user.home}/Downloads"
        contextOptions:
          acceptDownloads: true
          baseUrl: ${luma.url}
          #          bypassCSP: false
          #          proxy: "localhost://my.proxy/server"
          colorScheme: "dark"
          #          deviceScaleFactor: 1.0
          #          extraHTTPHeaders:
          #            key: "value"
          #            key1: "value1"
          #          forcedColors: "none"
          #          geolocation:
          #            latitude: 12.12
          #            longitude: 13.13
          #            accuracy: 1
          hasTouch: false
          #          httpCredentials:
          #            username: "user"
          #            password: "password"
          ignoreHTTPSErrors: true
          isMobile: false
          javaScriptEnabled: true
          locale: "en"
          offline: false
          #          permissions:
          #            - permission
          #            - permission1
          #          recordHarContent: "embed"
          #          recordHarMode: "full"
          #          recordHarOmitContent: false
          #          recordHarPath: "${user.home}/Downloads"
          #          recordHarUrlFilter: "filter"
          recordVideoDir: "${user.home}/Downloads"
          recordVideoSize:
            width: ${luma.userInterface.playwright.browser.width}
            height: ${luma.userInterface.playwright.browser.height}
          #          reducedMotion: "no_preference"
          screenSize:
            width: ${luma.userInterface.playwright.browser.width}
            height: ${luma.userInterface.playwright.browser.height}
          #          serviceWorkers: "allow"
          #          storageState: ""
          #          storageStatePath: "${user.home}/Downloads"
          strictSelectors: false
          #          timezoneId: 1
          userAgent: "windows"
          viewportSize:
            width: ${luma.userInterface.playwright.browser.width}
            height: ${luma.userInterface.playwright.browser.height}
pages:
  common:
    self: //div[@class='page-wrapper']
    header:
      self: ${pages.common.self}//header[@class='page-header']
      panel:
        self: ${pages.common.header.self}//div[@class='panel wrapper']
        links:
          self: ${pages.common.header.panel.self}//ul[@class='header links']
          welcomeMessage: ${pages.common.header.panel.links.self}//li[@class='greet welcome']//span
          signIn: ${pages.common.header.panel.links.self}//li[@class='authorization-link']
          signUp: ${pages.common.header.panel.links.self}//li//a[text()='Create an Account']
      content:
        self: //div[@class='header content']
        logo: ${pages.common.header.content.self}//a[@class='logo']
        searchForm:
          self: ${pages.common.header.content.self}//input[@id='search']
          searchButton: ${pages.common.header.content.self}//button[@class='action search']
          searchAutoComplete:
            self: ${pages.common.header.content.self}//div[contains(@class,'search-autocomplete')]
            items:
              self: //ul[@role='listbox']//li
              optionName: //span[@class='qs-option-name']
              amount: //span[@class='amount']
        cart: ${pages.common.header.content.self}//a[@class='action showcart']
      navigation:
        self: NAVIGATION
        items:
          self: LISTITEM
          menu:
            self: MENUITEM
            subMenu1:
              self: LISTITEM
              item: LISTITEM
            subMenu2:
              self: LISTITEM
              item: LISTITEM
  searchResults:
    self: //main[@id='maincontent']
    pageTitle: ${pages.searchResults.self}//h1/span
    results:
      self: ${pages.searchResults.self}//div[@class='column main']
      toolbar:
        self: ${pages.searchResults.results.self}//div[@class='toolbar toolbar-products']
        viewModes:
          self: //div[@class='modes']
          list: //span[text()='List']
          grid: //span[text()='Grid']
        amount:
          self: //p[@class='toolbar-amount']
        sorter:
          self: //div[contains(@class,'toolbar-sorter')]
          option: //select[@data-role='sorter']
          directionSwitcher: LINK
      relatedTermsBlock:
        self: ${pages.searchResults.results.self}//dl[@class='block']
      content:
        self: ${pages.searchResults.results.self}//div[contains(@class,'products wrapper')]
        items:
          self: LISTITEM
          product:
            image: IMG
            name: STRONG
            productReview:
              self: //div[contains(@class,'product-reviews-summary')]
              rating: //div[@class='rating-summary']
              review: //div[@class='reviews-actions']
            cost:
              self: //div[contains(@data-role,'priceBox')]
              priceLabel: //span[@class='price-label']
              price: //span[@class='price']
            availableSizes:
              self: //div[contains(@class,'swatch-attribute-options') and @aria-label='Size']
              availableSize: //div[@role='option']
            availableColors:
              self: //div[contains(@class,'swatch-attribute-options') and @aria-label='Color']
              availableColor: //div[@role='option']
            productActions:
              self: //div[contains(@class,'product actions')]
              addToCart: BUTTON
              addToWishList: Add to Wish List
              addToCompare: Add to Compare
            productDescription:
              self: //div[contains(@class,'product-item-description')]
              learnMore: LINK
    footer:
      self: ${pages.searchResults.results.self}/div[@class='toolbar toolbar-products']
      pages:
        self: //ul[@aria-labelledby='paging-label']
        next: //a[@title='Next']
        previous: //a[@title='Previous']
        current: //li[contains(@class,'item current')]//span[not(contains(@class,'label'))]
        pages: //li[contains(@class,'item') and (not(contains(@class,'pages-item-next') or contains(@class,'pages-item-previous')))]//span[not(contains(@class,'label'))]
      limiter: //select[@id='limiter']

